install:
  - ls .

script:
  - ./gradlew appengine-modules-ear:appengineExplodeApp
  - ls -lart

after_success:
  - if [ "${TRAVIS_BRANCH}" == "rc" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then .travis/deploy.sh; fi
