install:
  - echo "In install phase"

script:
  - echo "In script phase"
  - ./gradlew appengine-modules-ear:appengineExplodeApp


before_deploy:
  - echo "In before_deploy phase"
  - wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.23.zip
  - unzip -q appengine-java-sdk-1.9.23.zip
  - openssl aes-256-cbc -K $encrypted_a6c05f649a4b_key -iv $encrypted_a6c05f649a4b_iv -in .appcfg_oauth2_tokens_java.enc -out ~/.appcfg_oauth2_tokens_java -d
  #- cp .appcfg_oauth2_tokens_java ~

deploy:
  - if [ "${TRAVIS_BRANCH}" == "rc" ] -a [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
    appengine-java-sdk-1.9.23/bin/appcfg.sh update appengine-modules-ear/build/exploded-app
  - fi
